### ISSUE TITLE
PS3 on OFW

### ISSUE THREAD

**Issue by CrazyRedMachine** [Fredobedo/JVS2X#1]
Is this compatible with a PS3 console running on official firmware? or do you need homebrew to make it compatible?

**Comment by Fredobedo** [comment]
Yes it is compatible with official PS3, no need for a CFW for JVS2PS3 to work.
You may need a CFW PS3 if you have a PAL version and need to set it as an NTSC for outputing 640x480@60Hz

Best regards

**Comment by CrazyRedMachine** [comment]
this is great to hear, thanks :)
